export const content = {
  en: {
    skip: "Skip to content",
    langLabel: "Language",
    themeDark: "Switch to dark theme",
    themeLight: "Switch to light theme",
    menuOpen: "Open menu",
    menuClose: "Close menu",
    navLabel: "Sections",
    nav: {
      home: "Home",
      about: "About",
      work: "My Work",
      contact: "Contact",
    },
    hero: {
      label: "Creative Designer · Video Editor",
      first: "Ahmed",
      last: "Mahmoud",
      text: "Graphic designer and video editor creating bold visual identities, engaging content, and cinematic experiences.",
      work: "Explore My Work",
      contact: "Contact Me",
      imageAlt:
        "Ahmed Mahmoud in a neon studio, surrounded by design tools, film, and color grading",
    },
    about: {
      title: "About Me",
      imageAlt: "Ahmed Mahmoud brand mark, with a portrait emblem and AM monogram",
      caption: "Personal brand system",
      p1: "Ahmed Mahmoud is a graphic designer and video editor. He builds visual identities, social campaigns, and edits that carry a clear mood — from the first frame to the last color pass.",
      p2: "The work covers brand marks, posters, photo edits, motion, and video. Each piece is made to be seen quickly and remembered.",
      items: [
        "Graphic Design",
        "Video Editing",
        "Brand Identity",
        "Social Media Design",
        "Motion Graphics",
        "Visual Content",
        "Photo Editing",
        "Color Grading",
      ],
    },
    work: {
      kicker: "Selected works / 2026",
      titleLine1: "My",
      titleLine2: "Work",
      lede: "Selected visual work, designs and video projects.",
      photos: "Photos",
      videos: "Videos",
      view: "View",
      viewProject: "View project",
      featured: "Featured",
      play: "Play",
      videoLabel: "Video",
      emptyVideos: "Video projects will show up here.",
      close: "Close",
      prev: "Previous",
      next: "Next",
    },
    contact: {
      title: "Let's Create Something Great",
      text: "Have a project, campaign, or creative idea? Let's turn it into something visual.",
      whatsapp: "Let's Talk on WhatsApp",
      channels: [
        { id: "instagram", label: "Instagram" },
        { id: "facebook", label: "Facebook" },
        { id: "behance", label: "Behance" },
        { id: "linkedin", label: "LinkedIn" },
        { id: "email", label: "Email" },
        { id: "youtube", label: "YouTube" },
        { id: "tiktok", label: "TikTok" },
      ],
    },
    footer: {
      name: "Ahmed Mahmoud",
      role: "Graphic Designer & Video Editor",
      line: "Designing visuals. Editing stories. Creating impact.",
      rights: "All rights reserved.",
    },
  },
  ar: {
    skip: "تخطي إلى المحتوى",
    langLabel: "اللغة",
    themeDark: "التبديل إلى الوضع الداكن",
    themeLight: "التبديل إلى الوضع الفاتح",
    menuOpen: "فتح القائمة",
    menuClose: "إغلاق القائمة",
    navLabel: "الأقسام",
    nav: {
      home: "الرئيسية",
      about: "نبذة",
      work: "أعمالي",
      contact: "تواصل",
    },
    hero: {
      label: "مصمم جرافيك · مونتير فيديو",
      first: "Ahmed",
      last: "Mahmoud",
      text: "مصمم جرافيك ومونتير فيديو. أصنع هويات بصرية جريئة، ومحتوى يشد، وتجارب سينمائية.",
      work: "استعرض أعمالي",
      contact: "تواصل معي",
      imageAlt: "أحمد محمود في استوديو نيون، وسط أدوات التصميم والفيلم وتصحيح الألوان",
    },
    about: {
      title: "نبذة عني",
      imageAlt: "علامة أحمد محمود، شارة بورتريه وحرف AM",
      caption: "نظام الهوية الشخصية",
      p1: "أحمد محمود مصمم جرافيك ومونتير فيديو. يصنع هويات بصرية، وحملات للسوشيال، ومونتاج له مزاج واضح — من أول لقطة حتى آخر درجة لون.",
      p2: "الأعمال تشمل العلامات التجارية، والبوسترات، وتعديل الصور، والموشن، والفيديو. كل عمل يُصمَّم ليُرى بسرعة ويبقى في الذاكرة.",
      items: [
        "تصميم جرافيك",
        "مونتاج فيديو",
        "هوية بصرية",
        "تصميم سوشيال ميديا",
        "موشن جرافيك",
        "محتوى بصري",
        "تعديل صور",
        "تصحيح ألوان",
      ],
    },
    work: {
      kicker: "أعمال مختارة / 2026",
      titleLine1: "أعمالي",
      titleLine2: "",
      lede: "مجموعة مختارة من أعمال التصميم والمونتاج والمحتوى المرئي.",
      photos: "صور",
      videos: "فيديو",
      view: "عرض",
      viewProject: "عرض العمل",
      featured: "مميز",
      play: "تشغيل",
      videoLabel: "فيديو",
      emptyVideos: "ستظهر أعمال الفيديو هنا.",
      close: "إغلاق",
      prev: "السابق",
      next: "التالي",
    },
    contact: {
      title: "لنصنع شيئًا رائعًا معًا",
      text: "عندك مشروع، أو حملة، أو فكرة؟ نحولها إلى شيء بصري.",
      whatsapp: "نتكلم على واتساب",
      channels: [
        { id: "instagram", label: "إنستغرام" },
        { id: "facebook", label: "فيسبوك" },
        { id: "behance", label: "بيهانس" },
        { id: "linkedin", label: "لينكدإن" },
        { id: "email", label: "البريد" },
        { id: "youtube", label: "يوتيوب" },
        { id: "tiktok", label: "تيك توك" },
      ],
    },
    footer: {
      name: "Ahmed Mahmoud",
      role: "مصمم جرافيك ومونتير فيديو",
      line: "أصمّم الصورة. أحرّر الحكاية. أخلّف أثرًا.",
      rights: "جميع الحقوق محفوظة.",
    },
  },
}
